/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package stock;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author acer
 */
public class items extends javax.swing.JFrame {

    /**
     * Creates new form items
     */
    public items() throws Exception {
        initComponents();
        itemCode();
//        Customer reference number();
        fillTable();
        fillCmbName();

    }

    public void fillTable() throws Exception {
        ResultSet rs = JDBC.getdata("SELECT * FROM items");
        tblitems.setModel(DbUtils.resultSetToTableModel(rs));
    }

    public void fillCmb() throws Exception {

        ResultSet rs = JDBC.getdata("SELECT * FROM suppliers");
        System.out.println("Good here");
        while (rs.next()) {
            cmbsup.addItem(rs.getString("Name"));
        }
    }

    public void fillCmbName() throws Exception {

        ResultSet rs = JDBC.getdata("SELECT  Name FROM suppliers");
        System.out.println("Good here");
        while (rs.next()) {
            cmbsup.addItem(rs.getString("Name"));
        }
    }

    void itemCode() {
        try {
            ResultSet rs = JDBC.getdata("SELECT MAX(itemCode) FROM items");
            while (rs.next()) {
                String batch1 = rs.getString("MAX(itemCode)");
                int batch2 = Integer.parseInt(batch1.substring(3));
                int batch3 = (batch2 + 1);
                lbcode.setText("ITM" + batch3);
            }
        } catch (Exception e) {
            lbcode.setText("ITM" + 1001);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cmbtype = new javax.swing.JComboBox();
        txtrefno = new javax.swing.JTextField();
        txtqty = new javax.swing.JTextField();
        cmbsubitem = new javax.swing.JComboBox();
        txtdes = new javax.swing.JTextField();
        cmbsup = new javax.swing.JComboBox();
        txtprice = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnremove = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblitems = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        lbcode = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/rect.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arapey", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Inventory Items");

        jLabel12.setText("Logged in as Administrator");

        jButton4.setText("Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 204, 0));

        cmbtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mouse", "Keyboard", "Speakers", "Web cam", "Monitors", "RAM", "ROM", "DVD ROM", " " }));

        txtrefno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrefnoActionPerformed(evt);
            }
        });
        txtrefno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrefnoKeyTyped(evt);
            }
        });

        txtqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtyActionPerformed(evt);
            }
        });
        txtqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtqtyKeyTyped(evt);
            }
        });

        cmbsubitem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Camera", "Computers", "Server", "Laptops", "Network accessories" }));
        cmbsubitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbsubitemActionPerformed(evt);
            }
        });

        txtdes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdesKeyTyped(evt);
            }
        });

        cmbsup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbsup.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbsupPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbsup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbsupActionPerformed(evt);
            }
        });

        txtprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpriceKeyTyped(evt);
            }
        });

        jLabel16.setText("Customer reference number");

        jLabel14.setText("Purchased price");

        jLabel13.setText("Supplier");

        jLabel8.setText("Description");

        jCheckBox1.setText("sub item of");

        jLabel6.setText("Quantity");

        jLabel4.setText("itemCode");

        jLabel2.setText("Type");

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btnremove.setText("Remove");
        btnremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoveActionPerformed(evt);
            }
        });

        tblitems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "date added", "item code", "Description", "Quantity", "Sell price", "Purchase price", "Warranty due", "Status"
            }
        ));
        tblitems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblitemsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblitems);

        jButton2.setText("Demo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lbcode.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("REF");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(251, 251, 251)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addComponent(jLabel10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addGap(52, 52, 52))))
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(btnremove)
                        .addGap(64, 64, 64)
                        .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel16))
                                .addGap(138, 138, 138))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jCheckBox1)
                                .addGap(174, 174, 174)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtprice)
                                .addComponent(txtqty)
                                .addComponent(cmbsubitem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbtype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtdes)
                                .addComponent(cmbsup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtrefno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbcode, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(151, 151, 151)))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addGap(21, 21, 21)))
                .addGap(9, 9, 9)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(lbcode, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbsubitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtdes, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbsup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtrefno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jLabel16))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnclear)
                    .addComponent(btnremove)
                    .addComponent(btnupdate)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        new home().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtrefnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrefnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrefnoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
                    try {
                        JDBC.putdata("INSERT INTO items VALUES("
                                + "'" + lbcode.getText() + "',"
                                + "'" + cmbtype.getSelectedItem().toString() + "',"
                                + "'" + txtqty.getText() + "',"
                                + "'" + cmbsubitem.getSelectedItem().toString() + "',"
                                + "'" + txtdes.getText() + "',"
                                + "'" + cmbsup.getSelectedItem().toString() + "',"
                                + "'" + txtprice.getText() + "',"
                                + "'" + txtrefno.getText() + "'"
                                + ")");
                        lbcode.setText("");
                        txtqty.setText("");
                        txtdes.setText("");
                        txtprice.setText("");
                        txtrefno.setText("");

                        itemCode();
//                        Customer reference number();
                        fillTable();
                        JOptionPane.showMessageDialog(null, "Added sucessfully!");

                    } catch (Exception e) {
                        e.printStackTrace();
              }
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        lbcode.setText("");
        txtqty.setText("");
        txtdes.setText("");
        txtprice.setText("");
        txtrefno.setText("");

    }//GEN-LAST:event_btnclearActionPerformed

    private void btnremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoveActionPerformed
        try {
            int x = JOptionPane.showConfirmDialog(null, "Do you really want to delete?");

            if (x == 0) {

                JDBC.putdata("DELETE FROM items WHERE itemCode='" + lbcode.getText() + "'");
                fillTable();
                lbcode.setText("");
                txtqty.setText("");
                txtdes.setText("");
                txtprice.setText("");
                txtrefno.setText("");
            }
        } catch (Exception ex) {
            Logger.getLogger(items.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnremoveActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try {
            JDBC.putdata("UPDATE `8ware`.items SET `itemCode` = '" + lbcode.getText() + "',`type` = '" + cmbtype.getSelectedItem().toString() + "', `Quantity` = '" + txtqty.getText() + "', `Customer Reference number` = 76232, `sub item of` = '" + cmbsubitem.getSelectedItem().toString() + "', `Description` = '" + txtdes.getText() + "' WHERE `itemCode` = '" + lbcode.getText() + "'");
            lbcode.setText("");
            txtqty.setText("");
            txtdes.setText("");
            txtprice.setText("");
            txtrefno.setText("");
            fillTable();
            JOptionPane.showMessageDialog(null, "Updated sucessfully!");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void cmbsupPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbsupPopupMenuWillBecomeInvisible
    }//GEN-LAST:event_cmbsupPopupMenuWillBecomeInvisible

    private void tblitemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblitemsMouseClicked
        try {
            //JOptionPane.showMessageDialog(null,"here");
            int row = tblitems.getSelectedRow();
            //JOptionPane.showMessageDialog(null,"here too");
            String TC = (tblitems.getModel().getValueAt(row, 0).toString());
            // JOptionPane.showMessageDialog(null,"here then");
            ResultSet rs1 = JDBC.getdata("SELECT * FROM items WHERE itemCode ='" + TC + "'");
            //JOptionPane.showMessageDialog(null,"now here");


            if (rs1.next()) {
                //JOptionPane.showMessageDialog(null,"here");
                lbcode.setText(rs1.getString("itemCode"));

                txtqty.setText(rs1.getString("Quantity"));
                txtdes.setText(rs1.getString("Description"));
                txtprice.setText(rs1.getString("Purchased price"));
                txtrefno.setText(rs1.getString("Customer reference number"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblitemsMouseClicked

    private void cmbsubitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbsubitemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbsubitemActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtqty.setText("45");
        txtdes.setText("description");
        txtprice.setText("650.00");
        txtrefno.setText("1001");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtqtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtqtyKeyTyped
        char c = evt.getKeyChar();
        if ((Character.isDigit(c))) {
        } else {
            evt.consume();
        }
//        String s = txtqty.getText();
//        if (s.length() >= 10) {
//            evt.consume();
//        }
    }//GEN-LAST:event_txtqtyKeyTyped

    private void txtdesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdesKeyTyped
       char c = evt.getKeyChar();
        if (!(Character.isDigit(c))) {
        } else {
            evt.consume();
        }
//        String s = txtqty.getText();
////        if (s.length() >= 10) {
//            evt.consume();
//        }
    }//GEN-LAST:event_txtdesKeyTyped

    private void txtpriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpriceKeyTyped
       char c = evt.getKeyChar();
        if ((Character.isDigit(c))||c=='.') {
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txtpriceKeyTyped

    private void txtrefnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrefnoKeyTyped
         char c = evt.getKeyChar();
        if ((Character.isDigit(c))) {
        } else {
            evt.consume();
        }
        String s = txtrefno.getText();
        if (s.length() == 4) {
            evt.consume();
        }
    }//GEN-LAST:event_txtrefnoKeyTyped

    private void txtqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtyActionPerformed

    private void cmbsupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbsupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbsupActionPerformed

//    void supplierNo() {
//        try {
////            ResultSet rs = JDBC.getdata("SELECT MAX(Customer Reference number) FROM items");
////            while (rs.next()) {
////                String batch1 = rs.getString("MAX(sid)");
////                int batch2 = Integer.parseInt(batch1.substring(3));
////                int batch3 = (batch2 + 1);
//                txtrefno.setText("SUP" + batch3);
//            }
//        } catch (Exception e) {
//            txtrefno.setText("REF" + 1001);
//        }
//    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new items().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(items.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnremove;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox cmbsubitem;
    private javax.swing.JComboBox cmbsup;
    private javax.swing.JComboBox cmbtype;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbcode;
    private javax.swing.JTable tblitems;
    private javax.swing.JTextField txtdes;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txtrefno;
    // End of variables declaration//GEN-END:variables
}
