package CafetariaNTele;


import HRM.Login;
import java.awt.Component;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Visal
 */
public class Inventory_AddItem extends javax.swing.JFrame {

    /**
     * Creates new form Inventory_AddItem
     */
    public Inventory_AddItem() {
        initComponents();
        String name=ItmNameTxt.getText();
        String desc=DesTxt.getText();
        String manufac=(String) ManCmb.getSelectedItem();
        String pri = PriceTxt.getText();
        
        
        
        
        
        String query1="select UserName from 8ware.log";
        String sql ="SELECT * FROM 8ware.cafeteriaitems";
        String query2="select ItemID from 8ware.cafeteriaitems";
         String query3="select Name from 8ware.Manufacturer";
        
        try {
        Connection c = DBAccess.getConnection();
        Statement stmt = c.createStatement();
        Statement stm = c.createStatement();
        Statement st= c.createStatement();
            stmt.execute(query1);
            ResultSet rs = stmt.getResultSet();
            while (rs.next()) {
            String usr = rs.getString("UserName");
           UserLbl.setText(usr);
            }
            
            ResultSet rs1 = stm.executeQuery(sql);
           table1.setModel(DbUtils.resultSetToTableModel(rs1));
           //adding data to combo
           ResultSet rs2 = st.executeQuery(query2);
            while (rs2.next()) {
           ItmIDCmb.addItem(rs2.getString("ItemID"));
            }
            
            ResultSet rs3 = st.executeQuery(query3);
            while (rs3.next()) {
           ManCmb.addItem(rs3.getString("Name"));
            }
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UserLbl = new javax.swing.JLabel();
        HomeBtn = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        AddItemBtn1 = new javax.swing.JButton();
        PriceTxt = new javax.swing.JTextField();
        ManCmb = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        DesTxt = new javax.swing.JTextArea();
        ItmNameTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ItmNametxt2 = new javax.swing.JTextField();
        Mancombo = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        desTxt = new javax.swing.JTextArea();
        prTxt = new javax.swing.JTextField();
        DelBtn = new javax.swing.JButton();
        UpdBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ItmIDCmb = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 43)); // NOI18N
        jLabel2.setText("Cafeteria Inventory");

        jLabel3.setText("Logged in as ");

        UserLbl.setText("Admin");
        UserLbl.setName("userLabel"); // NOI18N

        HomeBtn.setText("Home");
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });

        LogoutBtn.setText("Logout");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Item Name");

        jLabel9.setText("Item Description");

        jLabel14.setText("Manufacturer");

        jLabel15.setText("Price");

        AddItemBtn1.setText("Add Item");
        AddItemBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemBtn1ActionPerformed(evt);
            }
        });

        PriceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceTxtActionPerformed(evt);
            }
        });

        ManCmb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManCmbMouseClicked(evt);
            }
        });
        ManCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManCmbActionPerformed(evt);
            }
        });

        DesTxt.setColumns(20);
        DesTxt.setRows(5);
        DesTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DesTxtMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(DesTxt);

        ItmNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmNameTxtActionPerformed(evt);
            }
        });

        jButton1.setText("Demo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(163, 163, 163)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ManCmb, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PriceTxt)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ItmNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(AddItemBtn1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(217, 217, 217))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItmNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ManCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(PriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddItemBtn1)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Item", jPanel1);

        jLabel10.setText("Item Name");

        jLabel12.setText("Item Description");

        jLabel16.setText("Manufacturer");

        jLabel17.setText("Price");

        ItmNametxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmNametxt2ActionPerformed(evt);
            }
        });

        Mancombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MancomboActionPerformed(evt);
            }
        });

        desTxt.setColumns(20);
        desTxt.setRows(5);
        jScrollPane3.setViewportView(desTxt);

        prTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prTxtActionPerformed(evt);
            }
        });

        DelBtn.setText("Delete");
        DelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelBtnActionPerformed(evt);
            }
        });

        UpdBtn.setText("Update");
        UpdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Item ID");

        ItmIDCmb.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ItmIDCmbMouseMoved(evt);
            }
        });
        ItmIDCmb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ItmIDCmbFocusGained(evt);
            }
        });
        ItmIDCmb.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                ItmIDCmbPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        ItmIDCmb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItmIDCmbMouseClicked(evt);
            }
        });

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                table1MouseMoved(evt);
            }
        });
        jScrollPane4.setViewportView(table1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(DelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(UpdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(114, 114, 114))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(185, 185, 185)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(prTxt)
                                .addComponent(ItmNametxt2)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                                .addComponent(Mancombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ItmIDCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ItmIDCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(ItmNametxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel16))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Mancombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UpdBtn)
                            .addComponent(DelBtn))
                        .addGap(48, 48, 48))))
        );

        jTabbedPane1.addTab("Update Item", jPanel2);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics1/rect.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(27, 27, 27)
                            .addComponent(UserLbl))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21)
                            .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(UserLbl)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        this.dispose();
        MainMenu m=new MainMenu();
        m.setVisible(true);
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
                   new Login().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void UpdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdBtnActionPerformed
        // TODO add your handling code here:
        String iname=ItmNametxt2.getText();
        String desc=desTxt.getText();
        String man=Mancombo.getSelectedItem().toString();
        String price=prTxt.getText();
        
        String id=ItmIDCmb.getSelectedItem().toString();

        
        System.out.println("good till here");
        if(price.contains(".*\\d.*")||(iname.equals(""))||desc.equals("")||(price.equals("")))
        {
            Component panel = null;
            JOptionPane.showMessageDialog(panel,"Invalid inputs entered", "Error", JOptionPane.ERROR_MESSAGE);
            ItmNameTxt.setText("");
            DesTxt.setText("");
            PriceTxt.setText("");
        }

        
        //
        else{

            String q="UPDATE 8ware.cafeteriaitems SET `ItemName` = '"+iname+"', `ItemDescription` = '"+desc+"', `Manufacturer` = '"+man+"',`Price`='"+price+"' WHERE `ItemID` = '"+id+"' ";

            try {
                Connection c = DBAccess.getConnection();
                Statement stmt = c.createStatement();
                stmt.executeUpdate(q);
                JOptionPane.showMessageDialog(this, "Success !");
                ItmNameTxt.setText("");
                DesTxt.setText("");
                PriceTxt.setText("");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_UpdBtnActionPerformed

    private void DelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelBtnActionPerformed
        // TODO add your handling code here:

        try {
            Connection c = DBAccess.getConnection();
            Statement stmt = c.createStatement();
            String a= ItmIDCmb.getSelectedItem().toString();
            String query2="delete from 8ware.cafeteriaitems where ItemID = '"+a+"'";
            //

            //adding data to combo
            stmt.executeUpdate(query2);
            JOptionPane.showMessageDialog(this, "Success");
            ItmNameTxt.setText("");
            DesTxt.setText("");
            PriceTxt.setText("");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_DelBtnActionPerformed

    private void prTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prTxtActionPerformed

    private void MancomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MancomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MancomboActionPerformed

    private void ItmNametxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmNametxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItmNametxt2ActionPerformed

    private void ItmNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItmNameTxtActionPerformed

    private void ManCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManCmbActionPerformed

    private void PriceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceTxtActionPerformed

    private void AddItemBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemBtn1ActionPerformed
        // TODO add your handling code here:
        
        String iname=ItmNameTxt.getText();
        String desc=DesTxt.getText();
        String man=ManCmb.getSelectedItem().toString();
        String price=PriceTxt.getText().toString();
        String ID="ITM"+((int)(Math.random()*9000)+1000);
        String qry="select ItemID from 8ware.cafeteriaitems";
        
        
        try {
                Connection c = DBAccess.getConnection();
                Statement stmt = c.createStatement();
                stmt.executeQuery(qry);
                //JOptionPane.showMessageDialog(this, "Success !");
                ResultSet rs = stmt.getResultSet ();
               
   while (rs.next ())
   {
       
       String ids = rs.getString ("iTEMid");
      
       if(ids==ID)
       {
           ID = "ITM"+((int)(Math.random()*9000)+1000);
       }
   }
                
                
              
                
            } catch (Exception e) {
                e.printStackTrace();
            }
        
        
        
        
        
        //else if()
//        else if(name.matches("^[0-9]+$")) {
//            Component panel = null;
//            JOptionPane.showMessageDialog(panel,"Invalid inputs entered", "Error", JOptionPane.ERROR_MESSAGE); 
//        }
       if(iname.equals(""))
        {
            Component panel = null;
            JOptionPane.showMessageDialog(panel,"Plese enter a valid Item Name", "Error", JOptionPane.ERROR_MESSAGE);
            ItmNameTxt.setText("");
            DesTxt.setText("");
            PriceTxt.setText("");
        }
       else if((desc.equals("")))
       {
           Component panel = null;
            JOptionPane.showMessageDialog(panel,"Please enter a valid Description", "Error", JOptionPane.ERROR_MESSAGE);
       }
       else if((price.contains(".*\\d.*"))||(price.equals("")))
       {
           Component panel = null;
            JOptionPane.showMessageDialog(panel,"Please enter a valid Price", "Error", JOptionPane.ERROR_MESSAGE);
       }
       else{
            String query="INSERT INTO 8ware.cafeteriaitems(`ItemID`,`ItemName`, `ItemDescription`,`Manufacturer`,`Price`) VALUES('"+ID+"','"+iname+"','"+desc+"','"+man+"',"+price+")";
            try {
                Connection c = DBAccess.getConnection();
                Statement stmt = c.createStatement();
                stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(this, "Success !");
                ItmNameTxt.setText("");
                DesTxt.setText("");
                PriceTxt.setText("");
                
                
              
                
            } catch (Exception e) {
                e.printStackTrace();
            }
       }
    }//GEN-LAST:event_AddItemBtn1ActionPerformed

    private void DesTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesTxtMouseClicked
     //    TODO add your handling code here:
//        initComponents();
//        String name=ItmNameTxt.getText();
//        String desc=DesTxt.getText();
//        String manufac=(String) ManCmb.getSelectedItem();
//        String pri = PriceTxt.getText();
//     
//     
//     if((name.equals(""))||(name.matches(".*\\d.*")))
//        {
//            //check = false;
//            Component panel = null;
//            JOptionPane.showMessageDialog(panel,"Please enter a valid Item Name", "Error", JOptionPane.ERROR_MESSAGE);
//     ItmNameTxt.setText("");
//        }
    }//GEN-LAST:event_DesTxtMouseClicked

    private void ManCmbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManCmbMouseClicked
        // TODO add your handling code here:
//        if((DesTxt.getText().equals(""))||(DesTxt.getText().matches(".*\\d.*")))
//        {
//            //check = false;
//            Component panel = null;
//            JOptionPane.showMessageDialog(panel,"Please enter a valid Des", "Error", JOptionPane.ERROR_MESSAGE);
//     ItmNameTxt.setText("");
//        }
    }//GEN-LAST:event_ManCmbMouseClicked

    private void table1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseMoved
        // TODO add your handling code here:
        try {
        Connection c = DBAccess.getConnection();
        Statement stmt = c.createStatement();
       
        String query1="select * from 8ware.cafeteriaitems";
        ResultSet rs1 = stmt.executeQuery(query1);
           table1.setModel(DbUtils.resultSetToTableModel(rs1));
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_table1MouseMoved

    private void ItmIDCmbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItmIDCmbMouseClicked
        // TODO add your handling code here:
        String id=ItmIDCmb.getSelectedItem().toString();
         String qrr="select * from 8ware.cafeteriaitems where ItemID = '"+id+"'";
        String query3="select Name from 8ware.Manufacturer";
        try {
            Connection c = DBAccess.getConnection();
            Statement stmt = c.createStatement();
            Statement st = c.createStatement();
            stmt.executeQuery(qrr);
            //JOptionPane.showMessageDialog(this, "Success !");
            ResultSet ns = stmt.getResultSet ();

            ns.next();
            String nm=ns.getString("ItemName");
            String ds=ns.getString("ItemDescription");
            String mn=ns.getString("Manufacturer");
            String pr=ns.getString("Price");
            
            ResultSet rs3 = st.executeQuery(query3);
            while (rs3.next()) {
           Mancombo.addItem(rs3.getString("Name"));
            }
            ItmNametxt2.setText(nm);
            desTxt.setText(ds);
            
            prTxt.setText(pr);
           
            //String qrnr="select * from 8ware.manufacturer where ManufactID = '"+manid+"'";
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_ItmIDCmbMouseClicked

    private void ItmIDCmbMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItmIDCmbMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ItmIDCmbMouseMoved

    private void ItmIDCmbPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ItmIDCmbPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String id=ItmIDCmb.getSelectedItem().toString();

        //String query="INSERT INTO 8ware.log(`UserName`, `Password`) VALUES ("+"\""+username+"\""+","+"\""+pwd+"\""+")";
        String qrr="select * from 8ware.cafeteriaitems where ItemID = '"+id+"'";
        String query3="select Name from 8ware.Manufacturer";
        try {
            Connection c = DBAccess.getConnection();
            Statement stmt = c.createStatement();
            Statement st = c.createStatement();
            stmt.executeQuery(qrr);
           // JOptionPane.showMessageDialog(this, "Success !");
            ResultSet ns = stmt.getResultSet ();

            ns.next();
            String nm=ns.getString("ItemName");
            String ds=ns.getString("ItemDescription");
            String mn=ns.getString("Manufacturer");
            String pr=ns.getString("Price");
            
            ResultSet rs3 = st.executeQuery(query3);
            while (rs3.next()) {
           Mancombo.addItem(rs3.getString("Name"));
            }
            ItmNametxt2.setText(nm);
            desTxt.setText(ds);
            
            prTxt.setText(pr);
           
            //String qrnr="select * from 8ware.manufacturer where ManufactID = '"+manid+"'";
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ItmIDCmbPopupMenuWillBecomeInvisible

    private void ItmIDCmbFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ItmIDCmbFocusGained
        // TODO add your handling code here:
        ItmIDCmb.removeAllItems();
        try {
            Connection c = DBAccess.getConnection();
            Statement stmt = c.createStatement();
            Statement stm = c.createStatement();
            Statement st = c.createStatement();
            Statement s1 = c.createStatement();
            String query2="select ItemID from 8ware.cafeteriaitems";
            //

            //adding data to combo
            ResultSet rs2 = st.executeQuery(query2);
            while (rs2.next()) {
                ItmIDCmb.addItem(rs2.getString("ItemID"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ItmIDCmbFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ItmNameTxt.setText("DemoItem");
        DesTxt.setText("DemoDescription");
        PriceTxt.setText("100");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ItmNameTxt.setText("");
        DesTxt.setText("");
        PriceTxt.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory_AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory_AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory_AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory_AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory_AddItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddItemBtn1;
    private javax.swing.JButton DelBtn;
    private javax.swing.JTextArea DesTxt;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JComboBox<String> ItmIDCmb;
    private javax.swing.JTextField ItmNameTxt;
    private javax.swing.JTextField ItmNametxt2;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JComboBox<String> ManCmb;
    private javax.swing.JComboBox<String> Mancombo;
    private javax.swing.JTextField PriceTxt;
    private javax.swing.JButton UpdBtn;
    private javax.swing.JLabel UserLbl;
    private javax.swing.JTextArea desTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField prTxt;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
