/*
 * EmployeeRegistration.java
 *
 * Created on July 26, 2016, 1:42 AM
 */

package HRM;

import Forms.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author  dell notebook
 */
public class AddUser extends javax.swing.JFrame {

    /** Creates new form EmployeeRegistration */
    public AddUser() {
        initComponents();
         cmdEmp.setSelectedIndex(0);
         txtPw.setText("");
                try {
                   
            Connection c=DBAccess.getConnection();
    Statement s=c.createStatement();
    ResultSet rs=s.executeQuery("select * from employee");
            Vector v = new Vector();
            while (rs.next()) {
                v.add(rs.getString("emp_id"));
            }
            cmdEmp.setModel(new DefaultComboBoxModel(v));

        } catch (Exception e) {
            e.printStackTrace();
        }
        
        //txtName.setEnabled(false);
    }
    /*public ResultSet getEmployee() throws Exception
    {
    Connection c=DBAccess.getConnection();
    Statement s=c.createStatement();
    ResultSet rs=s.executeQuery("select * from employee");
    return rs;
    }
    public void fillEmployee()throws Exception
    {
    ResultSet f=getEmployee();
    while(f.next())
    {
    cmdEmp.addItem(f.getString(1));
    fillEmployee();
    }
    }*/
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lblUser_Name = new javax.swing.JLabel();
        txtPw = new javax.swing.JTextField();
        lblPw = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        cmdEmp = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("8WARE TOTAL MANAGEMENT SYSTEM");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 20, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Add User");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Logged in as Admin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("Logout");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 60, 20));

        jSeparator2.setForeground(new java.awt.Color(51, 153, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 700, 10));

        lblUser_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUser_Name.setText("User Name");
        getContentPane().add(lblUser_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        txtPw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 220, -1));

        lblPw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPw.setText("Password");
        getContentPane().add(lblPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, -1, -1));

        cmdEmp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdEmp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select User Name", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmdEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 220, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/rect.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(806, 495));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
// TODO add your handling code here:
    Add();
}//GEN-LAST:event_btnAddActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    new Login().setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed
public void Add()
{
    try {
         Connection c=DBAccess.getConnection();
         Statement s=c.createStatement();
         s.executeUpdate("insert into user values('"+cmdEmp.getSelectedItem().toString()+"','"+txtPw.getText()+"')");
         JOptionPane.showMessageDialog(rootPane, "Saved !!! ");
         cmdEmp.setSelectedIndex(0);
         txtPw.setText("");
         
    
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUser().setVisible(true);
            }
        });
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox cmdEmp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblPw;
    private javax.swing.JLabel lblUser_Name;
    private javax.swing.JTextField txtPw;
    // End of variables declaration//GEN-END:variables

}
