/*
 * EmployeeRegistration.java
 *
 * Created on July 26, 2016, 1:42 AM
 */

package HRM;

/**
 *
 * @author  dell notebook
 */
public class EMPHOME extends javax.swing.JFrame {

    String emp_id;
    /** Creates new form EmployeeRegistration */
    
    public EMPHOME() {
    initComponents();
    //txtName.setEnabled(false);
    }
        public EMPHOME(String p) {
        initComponents();
        emp_id=p;
        //txtName.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnAdd_and_Check_Loans = new javax.swing.JButton();
        btnView_Profile = new javax.swing.JButton();
        btnAdd_and_Check_Leaves = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("8WARE TOTAL MANAGEMENT SYSTEM");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 20, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Home");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Logged in as Employer");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("Logout");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 60, 20));

        jSeparator2.setForeground(new java.awt.Color(51, 153, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 700, 10));

        btnAdd_and_Check_Loans.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdd_and_Check_Loans.setText("Add and Check Loans");
        btnAdd_and_Check_Loans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_and_Check_LoansActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd_and_Check_Loans, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        btnView_Profile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnView_Profile.setText("View Profile");
        btnView_Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView_ProfileActionPerformed(evt);
            }
        });
        getContentPane().add(btnView_Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 140, -1));

        btnAdd_and_Check_Leaves.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdd_and_Check_Leaves.setText("Add and Check Leaves");
        btnAdd_and_Check_Leaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_and_Check_LeavesActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd_and_Check_Leaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/rect.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(806, 495));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void btnAdd_and_Check_LeavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_and_Check_LeavesActionPerformed
// TODO add your handling code here:
    new AddandCheckLeaves(emp_id).setVisible(true);
    this.dispose();
}//GEN-LAST:event_btnAdd_and_Check_LeavesActionPerformed

private void btnAdd_and_Check_LoansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_and_Check_LoansActionPerformed
// TODO add your handling code here:
    new AddandCheckLoans(emp_id).setVisible(true);
    this.dispose();
}//GEN-LAST:event_btnAdd_and_Check_LoansActionPerformed

private void btnView_ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView_ProfileActionPerformed
// TODO add your handling code here:
    new View_Profile(emp_id).setVisible(true);
    this.dispose();
}//GEN-LAST:event_btnView_ProfileActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    new Login().setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EMPHOME().setVisible(true);
            }
        });
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd_and_Check_Leaves;
    private javax.swing.JButton btnAdd_and_Check_Loans;
    private javax.swing.JButton btnView_Profile;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

}
