/*
 * EmployeeRegistration.java
 *
 * Created on July 26, 2016, 1:42 AM
 */

package HRM;
//import OOPCLASSES.EmployeeRegistrationOO;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/**
 *
 * @author  dell notebook
 */
public class EmployeeRegistration extends javax.swing.JFrame {
    String gender;
    String emp_id;
//EmployeeRegistrationOO er= new EmployeeRegistrationOO();
validate check=new validate();
DBAccess db = new DBAccess();
    /** Creates new form EmployeeRegistration */
    public EmployeeRegistration() {
        initComponents();
        
    
        btnDemo.setVisible(true);
        
        txtAddress.setText("");
        txtEmail.setText("");
        txtID.setText("");
        txtPhone.setText("");
        txtName.setText("");
        txtPhone.setText("");
        txtNIC.setText("");
        cmbDepartment.setSelectedIndex(0);
        cmbDesignation.setSelectedIndex(0);
        cmbType.setSelectedIndex(0);
        
        chFemale.setSelected(false);
        chMale.setSelected(false);
        
        lblErrorAddress.setText("");
        lblErrorEmail.setText("");
        lblErrorID.setText("");
        lblErrorNIC.setText("");
        lblErrorName.setText("");
        lblErrorPhone.setText("");
        ButtonGroup bg = new ButtonGroup();
        bg.add(chFemale);
        bg.add(chMale);
        
    }
    
 

    public void clear()
    {
        txtAddress.setText("");
        txtEmail.setText("");
        txtID.setText("");
        txtPhone.setText("");
        txtName.setText("");
        txtPhone.setText("");
        txtNIC.setText("");
        cmbDepartment.setSelectedIndex(0);
        cmbDesignation.setSelectedIndex(0);
        cmbType.setSelectedIndex(0);
        chFemale.setSelected(false);
        chMale.setSelected(false);
       
        
        lblErrorAddress.setText("");
        lblErrorEmail.setText("");
        lblErrorID.setText("");
        lblErrorNIC.setText("");
        lblErrorName.setText("");
        lblErrorPhone.setText("");
       // ButtonGroup bg = new ButtonGroup();
        
       /* bg.add(chMale);
                if (chMale.isSelected()) 
        {
            
            chFemale.setSelected(false);
        } 
        else if (chFemale.isSelected()) 
        {
           
           chMale.setSelected(false);
        }*/
    }

    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lblErrorPhone = new javax.swing.JLabel();
        lblErrorID = new javax.swing.JLabel();
        lblErrorName = new javax.swing.JLabel();
        lblErrorAddress = new javax.swing.JLabel();
        lblErrorEmail = new javax.swing.JLabel();
        lblErrorNIC = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        lblNIC = new javax.swing.JLabel();
        txtNIC = new javax.swing.JTextField();
        chFemale = new javax.swing.JRadioButton();
        chMale = new javax.swing.JRadioButton();
        lblDesignation1 = new javax.swing.JLabel();
        cmbDesignation = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        lblDepartment1 = new javax.swing.JLabel();
        cmbDepartment = new javax.swing.JComboBox();
        cmbType = new javax.swing.JComboBox();
        lblType = new javax.swing.JLabel();
        btnDemo = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("8WARE TOTAL MANAGEMENT SYSTEM");
        setExtendedState(6);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 20, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Register Employee ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Logged in as Employer Manager");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 80, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 153));
        jButton2.setText("Home");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 110, 60, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("Logout");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 110, 60, 20));

        jSeparator2.setForeground(new java.awt.Color(51, 153, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 1300, 10));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblErrorPhone.setForeground(new java.awt.Color(204, 51, 0));
        lblErrorPhone.setText("*");
        jPanel1.add(lblErrorPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 260, -1));

        lblErrorID.setForeground(new java.awt.Color(204, 51, 0));
        lblErrorID.setText("*");
        jPanel1.add(lblErrorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 330, -1));

        lblErrorName.setForeground(new java.awt.Color(204, 51, 0));
        lblErrorName.setText("*");
        jPanel1.add(lblErrorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 330, -1));

        lblErrorAddress.setForeground(new java.awt.Color(204, 51, 0));
        lblErrorAddress.setText("*");
        jPanel1.add(lblErrorAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 330, -1));

        lblErrorEmail.setForeground(new java.awt.Color(204, 51, 0));
        lblErrorEmail.setText("*");
        jPanel1.add(lblErrorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 260, -1));

        lblErrorNIC.setForeground(new java.awt.Color(204, 51, 0));
        lblErrorNIC.setText("*");
        jPanel1.add(lblErrorNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 260, -1));

        lblId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblId.setText("Employee ID");
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txtID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtIDMouseExited(evt);
            }
        });
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        txtID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIDFocusLost(evt);
            }
        });
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDKeyReleased(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 190, -1));

        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblName.setText("Employee Name");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 190, -1));

        lblAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAddress.setText("Address");
        jPanel1.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        txtAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAddressFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(txtAddress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 190, -1));

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("Email");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 190, -1));

        lblPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPhone.setText("Phone");
        jPanel1.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        txtPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPhoneFocusLost(evt);
            }
        });
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhoneKeyReleased(evt);
            }
        });
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 190, -1));

        lblGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGender.setText("Gender");
        jPanel1.add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        lblNIC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNIC.setText("NIC");
        jPanel1.add(lblNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        txtNIC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNIC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNICFocusLost(evt);
            }
        });
        jPanel1.add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 190, -1));

        chFemale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chFemale.setText("Female");
        chFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chFemaleActionPerformed(evt);
            }
        });
        chFemale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                chFemaleKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                chFemaleKeyReleased(evt);
            }
        });
        jPanel1.add(chFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        chMale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chMale.setText("Male");
        chMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chMaleActionPerformed(evt);
            }
        });
        chMale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                chMaleKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                chMaleKeyReleased(evt);
            }
        });
        jPanel1.add(chMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, -1, -1));

        lblDesignation1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDesignation1.setText("Designation");
        jPanel1.add(lblDesignation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        cmbDesignation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbDesignation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a designation", "employee", "manager", "technician", "driver" }));
        cmbDesignation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDesignationItemStateChanged(evt);
            }
        });
        cmbDesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDesignationActionPerformed(evt);
            }
        });
        jPanel1.add(cmbDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 750, 370));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Department Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDepartment1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDepartment1.setText("Department");
        jPanel2.add(lblDepartment1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        cmbDepartment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbDepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a department", "HR", "Accounts", "Technical", "Marketing" }));
        cmbDepartment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDepartmentItemStateChanged(evt);
            }
        });
        cmbDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDepartmentActionPerformed(evt);
            }
        });
        jPanel2.add(cmbDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 190, -1));

        cmbType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a type", "Training", "Probation", "Temporary", "Permanent" }));
        cmbType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTypeItemStateChanged(evt);
            }
        });
        cmbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeActionPerformed(evt);
            }
        });
        jPanel2.add(cmbType, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 190, -1));

        lblType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblType.setText("Type");
        jPanel2.add(lblType, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 160, 440, 370));

        btnDemo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDemo.setText("DEMO");
        btnDemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDemoActionPerformed(evt);
            }
        });
        getContentPane().add(btnDemo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 590, -1, -1));

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 590, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/rect.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1725, 855));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
// TODO add your handling code here:
    //going to the db
//    try 
//    {
//        
//        
//        /*File f = jFileChooser1.getSelectedFile();
//        String path = f.getAbsolutePath();
//        path = path.replace("\\", "/");
//        er.setPath(path);*/
//         
//         
//        if (chMale.isSelected()) 
//        {
//            er.setGender("Male");
//        } else if (chFemale.isSelected()) 
//        {
//            er.setGender("Female");
//        }
//        
//        //er.setID(txtID.getText());
//        er.setName(txtName.getText());
//        er.setAddress(txtAddress.getText());
//        er.setEmail(txtEmail.getText());
//        er.setNIC(txtPhone.getText());
//        er.setPhone(txtPhone.getText());
//        er.setDeptType(cmbType.getSelectedItem().toString());
//        er.setDesignation(cmbDesignation.getSelectedItem().toString());
//        er.setDepartment(cmbDepartment.getSelectedItem().toString());
//        
//        er.save();
//        JOptionPane.showMessageDialog(rootPane, "Saved !!!");
//        
//    } 
//    catch (Exception e) 
//    {
//        e.printStackTrace();
//    }
    
    try {
        if (chMale.isSelected()) 
        {
            gender="Male";
            chFemale.setSelected(false);
        } 
         if (chFemale.isSelected()) 
        {
           gender="Female";
           chMale.setSelected(false);
        }
        
        if ( check.isEmpty(gender) ) 
        {
            JOptionPane.showMessageDialog(rootPane, "Pls select a gender !!");
        }
         /*if((cmbType.getSelectedItem().toString().equals("Select a type")))
        {
            JOptionPane.showMessageDialog(rootPane, "Select a type");
        }*/
                 if((cmbDesignation.getSelectedItem().toString().equals("Select a designation")))
        {
            JOptionPane.showMessageDialog(rootPane, "Select a designation");
        }
         else 
        {
            Connection c = DBAccess.getConnection();
            Statement s = c.createStatement();
            s.executeUpdate("Insert into employee values('" + txtID.getText() + "','" + txtNIC.getText() + "','" + txtPhone.getText() + "','" + cmbDesignation.getSelectedItem().toString() + "','" + cmbDepartment.getSelectedItem().toString() + "','" + cmbType.getSelectedItem().toString() + "','" + txtName.getText() + "','" + txtAddress.getText() + "','" + txtEmail.getText() + "','" + gender + "')");
            JOptionPane.showMessageDialog(rootPane, "Saved !!!");
            clear();
        }
        
    } catch (Exception e) {
        e.printStackTrace();
    }

}//GEN-LAST:event_btnSaveActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    new EMPMANAGERHOME().setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

private void txtIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyReleased
// TODO add your handling code here:
/*String ID=txtID.getText();
    //int size = str.length();
    char[] arr = ID.toCharArray();
    
    if(arr.length>10)
    JOptionPane.showMessageDialog(rootPane, "Too Long");
    //Validating Employee ID as tech,emp
    if(!((arr[0]=='t'&& arr[1]=='e' && arr[2]=='c'&& arr[3]=='h') ||(arr[0]=='e'&& arr[1]=='m' && arr[2]=='p')) )
    {
    JOptionPane.showMessageDialog(rootPane, "Invalid Extention");
    txtID.setText("");
    }
    else
    {
    er.setID(txtID.getText());
    }*/
}//GEN-LAST:event_txtIDKeyReleased

private void txtPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyReleased
// TODO add your handling code here:
 
}//GEN-LAST:event_txtPhoneKeyReleased

private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
// TODO add your handling code here:
    
}//GEN-LAST:event_txtEmailKeyReleased

private void chFemaleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chFemaleKeyPressed
// TODO add your handling code here:

}//GEN-LAST:event_chFemaleKeyPressed

private void chMaleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chMaleKeyPressed
// TODO add your handling code here:

}//GEN-LAST:event_chMaleKeyPressed

private void chFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chFemaleActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_chFemaleActionPerformed

private void chFemaleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chFemaleKeyReleased
// TODO add your handling code here:
    if (chFemale.isSelected()) {
        chFemale.setSelected(true);
        chMale.setSelected(false);
    } else {
        chMale.setSelected(true);
        chFemale.setSelected(false);
    }

}//GEN-LAST:event_chFemaleKeyReleased

private void chMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chMaleActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_chMaleActionPerformed

private void chMaleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chMaleKeyReleased
// TODO add your handling code here:
    if (chMale.isSelected()) {
        chMale.setSelected(true);
        chFemale.setSelected(false);
    } else {
        chFemale.setSelected(true);
        chMale.setSelected(false);
    }
}//GEN-LAST:event_chMaleKeyReleased

private void btnDemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemoActionPerformed
// TODO add your handling code here:
       try {
          txtAddress.setText("Nugegoda");
        txtEmail.setText("amal@gmail.com");
       // txtID.setText("");
        txtPhone.setText("0773916845");
        txtName.setText("Amal");
        txtNIC.setText("953216548v");
        cmbDepartment.setSelectedIndex(1);
        //cmbDesignation.setSelectedIndex(0);
        cmbType.setSelectedIndex(1);
        chFemale.setSelected(false);
        chMale.setSelected(true);
       
        
        lblErrorAddress.setText("");
        lblErrorEmail.setText("");
        lblErrorID.setText("");
        lblErrorNIC.setText("");
        lblErrorName.setText("");
        lblErrorPhone.setText("");
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_btnDemoActionPerformed

private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
// TODO add your handling code here:
    
}//GEN-LAST:event_txtNameKeyPressed

private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
// TODO add your handling code here:


}//GEN-LAST:event_txtNameActionPerformed

private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
// TODO add your handling code here:


}//GEN-LAST:event_txtNameFocusGained

private void txtIDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDMouseExited
// TODO add your handling code here:

}//GEN-LAST:event_txtIDMouseExited

private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
// TODO add your handling code here:
    
}//GEN-LAST:event_txtIDActionPerformed

private void txtIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDFocusLost
// TODO add your handling code here:

    try {
        if(check.isEmpty(txtID.getText()))
        {
            JOptionPane.showMessageDialog(rootPane, "Pls fill  the ID field !!");
        }
        if(check.isID(txtID.getText()))
        {
            JOptionPane.showMessageDialog(rootPane, "Pls enter a valid id !!");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

}//GEN-LAST:event_txtIDFocusLost

private void txtIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDFocusGained
// TODO add your handling code here:

}//GEN-LAST:event_txtIDFocusGained

private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
// TODO add your handling code here:
     try {
        if(check.isEmpty(txtName.getText()))
        {
            JOptionPane.showMessageDialog(rootPane, "Pls fill  the Name field !!");
        }
        if(!check.isLetter(txtName.getText()))
        {
            JOptionPane.showMessageDialog(rootPane, "Pls enter only letters  for name !!");
            txtName.setText("");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_txtNameFocusLost

private void txtAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusLost
// TODO add your handling code here:
         try {
        if(check.isEmpty(txtAddress.getText()))
        {
            JOptionPane.showMessageDialog(rootPane, "Pls fill  the Address field !!");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_txtAddressFocusLost

private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
// TODO add your handling code here:
          try {
              if (check.isEmpty(txtEmail.getText())) {
                  JOptionPane.showMessageDialog(rootPane, "Pls fill  the Email field !!");
              }
              if (!check.isValidEmailAddress(txtEmail.getText())) {
                  JOptionPane.showMessageDialog(rootPane, "Pls enter a valid email !!");

              }
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_txtEmailFocusLost

private void txtNICFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNICFocusLost
// TODO add your handling code here:
              try {
        if(check.isEmpty(txtNIC.getText()))
        {
            JOptionPane.showMessageDialog(rootPane, "Pls fill  the NIC field !!");
        }
        if(!check.isNIC(txtNIC.getText()))
        {
            JOptionPane.showMessageDialog(rootPane, "Pls enter a valid nic !!");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_txtNICFocusLost

private void txtPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusLost
// TODO add your handling code here:
    try {
        if (check.isEmpty(txtPhone.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Pls fill  the Phone field !!");
        }
        if (!check.isNumeric(txtPhone.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Pls enter only letters  phone !!");
        }
        if (!check.isPhoneNumberLenth(txtPhone.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Pls enter only 10 letters for the Phone field !!");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_txtPhoneFocusLost

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    new Login().setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed

private void cmbDesignationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDesignationItemStateChanged
// TODO add your handling code here:
try {
    
    String cha;
    int count = 0;
    String scount;
    
    String desi = cmbDesignation.getSelectedItem().toString();
    
      if (desi.equals("employee")) {
    cha = "E";
    txtID.setText(cha);
    
    Connection c = DBAccess.getConnection();
    Statement s = c.createStatement();
    ResultSet rs = s.executeQuery("select count(emp_id)as count from employee where emp_id LIKE '" + cha + "%' ");
    while (rs.next()) {
    count = (Integer.parseInt(rs.getString("count"))) + 1;
    scount = Integer.toString(count);
    txtID.setText(cha + "00" + scount);
    }
    
    } else if (desi.equals("manager")) {
    cha = "M";
    txtID.setText(cha);
    
    Connection c = DBAccess.getConnection();
    Statement s = c.createStatement();
    ResultSet rs = s.executeQuery("select count(emp_id)as count from employee where emp_id LIKE '" + cha + "%' ");
    while (rs.next()) {
    count = (Integer.parseInt(rs.getString("count"))) + 1;
    scount = Integer.toString(count);
    txtID.setText(cha + "00" + scount);
    }
    } else if (desi.equals("technician")) {
    cha = "T";
    txtID.setText(cha);
    
    Connection c = DBAccess.getConnection();
    Statement s = c.createStatement();
    ResultSet rs = s.executeQuery("select count(emp_id)as count from employee where emp_id LIKE '" + cha + "%' ");
    while (rs.next()) {
    count = (Integer.parseInt(rs.getString("count"))) + 1;
    scount = Integer.toString(count);
    txtID.setText(cha + "000" + scount);
    }
    } else if (desi.equals("driver")) {
    cha = "T";
    txtID.setText(cha);
    
    Connection c = DBAccess.getConnection();
    Statement s = c.createStatement();
    ResultSet rs = s.executeQuery("select count(emp_id)as count from employee where emp_id LIKE '" + cha + "%' ");
    while (rs.next()) {
    count = (Integer.parseInt(rs.getString("count"))) + 1;
    scount = Integer.toString(count);
    txtID.setText(cha + "00" + scount);
    }
    }
    
    } catch (Exception e) {
    e.printStackTrace();
    }
}//GEN-LAST:event_cmbDesignationItemStateChanged

private void cmbDepartmentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDepartmentItemStateChanged
// TODO add your handling code here:

}//GEN-LAST:event_cmbDepartmentItemStateChanged

private void cmbTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTypeItemStateChanged
// TODO add your handling code here:
       
}//GEN-LAST:event_cmbTypeItemStateChanged

private void cmbDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDepartmentActionPerformed
// TODO add your handling code here:
        try {
        if((cmbDesignation.getSelectedItem().toString().equals("Select a department")))
        {
            JOptionPane.showMessageDialog(rootPane, "Select a department");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_cmbDepartmentActionPerformed

private void cmbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeActionPerformed
// TODO add your handling code here:
/*try {
    if((cmbDesignation.getSelectedItem().toString().equals("Select a type")))
    {
    JOptionPane.showMessageDialog(rootPane, "Select a type");
    }
    } catch (Exception e) {
    e.printStackTrace();
    }*/
}//GEN-LAST:event_cmbTypeActionPerformed

private void cmbDesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDesignationActionPerformed
// TODO add your handling code here:

}//GEN-LAST:event_cmbDesignationActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeRegistration().setVisible(true);
            }
        });
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDemo;
    private javax.swing.JButton btnSave;
    private javax.swing.JRadioButton chFemale;
    private javax.swing.JRadioButton chMale;
    private javax.swing.JComboBox cmbDepartment;
    private javax.swing.JComboBox cmbDesignation;
    private javax.swing.JComboBox cmbType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblDepartment1;
    private javax.swing.JLabel lblDesignation1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblErrorAddress;
    private javax.swing.JLabel lblErrorEmail;
    private javax.swing.JLabel lblErrorID;
    private javax.swing.JLabel lblErrorNIC;
    private javax.swing.JLabel lblErrorName;
    private javax.swing.JLabel lblErrorPhone;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNIC;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblType;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables

}
