 package HRM;

import Forms.*;
import Sales.TabbedPaneWin;
import java.sql.ResultSet;

;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Visal
 */
    import java.awt.Toolkit;
    import java.awt.event.WindowEvent;
    import javax.swing.JOptionPane;
    import java.awt.Component;
import java.sql.Connection;
       import java.sql.DriverManager;

import java.sql.SQLException;
import java.sql.Statement;
import static java.sql.Types.VARCHAR;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Toolkit;
    import java.awt.event.WindowEvent;
    import javax.swing.JOptionPane;
    import java.awt.Component;
import java.sql.Connection;
       import java.sql.DriverManager;

import java.sql.Statement;
import static java.sql.Types.VARCHAR;
public class Login extends javax.swing.JFrame {
 String uname,pw,txtpw;
 char ch;
 boolean status;
    /**
     * Creates new form Login
     */
    
    public Login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClsBtn = new javax.swing.JButton();
        lgnBtn = new javax.swing.JButton();
        PwdTxt = new javax.swing.JPasswordField();
        userTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usrTxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setName("lgnFrame"); // NOI18N

        ClsBtn.setText("Close");
        ClsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClsBtnActionPerformed(evt);
            }
        });

        lgnBtn.setText("Login");
        lgnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgnBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("User Name");

        jLabel3.setText("Password");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("LOGIN");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics1/Lohin.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(usrTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 511, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(ClsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(lgnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(PwdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(usrTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(ClsBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PwdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lgnBtn))
                    .addComponent(jLabel2)
                    .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(684, 316));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public boolean checkUser()
{
    //System.out.println("S1");
    try {
         //System.out.println("S2");
    Connection c=DBAccess.getConnection();
    Statement s=c.createStatement();
        //System.out.println("S3");
    ResultSet rs=s.executeQuery("Select * from user where uname='"+userTxt.getText().toString()+"'");
        System.out.println("usr : " + userTxt.getText());
    txtpw=(PwdTxt.getText());
    status=rs.next();
        System.out.println("S4 : " + status);
    if(status)
    {
        rs.previous();
        while (rs.next()) {
            uname = rs.getString("uname");
            pw = rs.getString("pw");
            System.out.println("pw : "+ pw + " ,, "+ txtpw);
            if (txtpw.equals(pw)) {
                status = true;
            } else {
                status = false;
            }
        }
    }
    else
    {
        JOptionPane.showMessageDialog(rootPane, "Invalid User Name !!! ");
        status=false;
        userTxt.setText("");
        PwdTxt.setText("");
    }
    } catch (Exception e) {
        e.printStackTrace();
    }
    System.out.println("Status " + status);
   return status;
    
}
    private void lgnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgnBtnActionPerformed
        // TODO add your handling code here:
       
        //System.out.println(uname);
        //System.out.println(pw);
        
        
        //boolean b=;
        if(checkUser())
        {
             if((uname.equals("hrm")))
        {
            EMPMANAGERHOME m= new EMPMANAGERHOME();
            this.dispose();
            m.setVisible(true);
        }
        else if((uname.charAt(0)=='E') || (uname.charAt(0)=='T') || (uname.charAt(0)=='M'))
        {
            EMPHOME m= new EMPHOME(uname);
            this.dispose();
            m.setVisible(true);
        }
        
        else if((uname.equals("Admin")))
        {
            Admin a= new Admin();
            this.dispose();
            a.setVisible(true);
        }
   
                     else if((uname.equals("Cafe")))
        {
            CafetariaNTele.MainMenu m= new CafetariaNTele.MainMenu();
            this.dispose();
            m.setVisible(true);
        }
        
        
        
        else if((uname.equals("stock")))
        {
            stock.home m= new stock.home();
            this.dispose();
            m.setVisible(true);
        }
        
        else if((uname.equals("accounts")))
        {
            accounts.First m= new accounts.First();
            this.dispose();
            m.setVisible(true);
        }
        
        else if((uname.equals("fleet")))
        {
            try {
                Fleet.home m= new Fleet.home();
                this.dispose();
                m.setVisible(true);
            } catch (Exception e) {
                //Logger.getLogger(login.Login.class.getName()).log(Level.SEVERE, null, ex);
                e.printStackTrace();
            }
        }
        else if((uname.equals("jobs")))
        {
            Services.ServiceManagement m;
            try {
                m = new Services.ServiceManagement();
                m.setVisible(true);
            } catch (Exception e) {
                //Logger.getLogger(login.Login.class.getName()).log(Level.SEVERE, null, ex);
                e.printStackTrace();
            }
            this.dispose();
            
        }
        
        else if((uname.equals("sales")))
        {
            TabbedPaneWin m;
            try {
                m = new TabbedPaneWin();
                 m.setVisible(true);
            } catch (Exception e) {
                //Logger.getLogger(login.Login.class.getName()).log(Level.SEVERE, null, ex);
                e.printStackTrace();
            }
            this.dispose();
           
        }
        
        else if((uname.equals("tele")))
        {
            try {
                CafetariaNTele.TeleMarketing m= new CafetariaNTele.TeleMarketing();
                m.setVisible(true);
                this.dispose();
            } catch (Exception e) {
                //Logger.getLogger(login.Login.class.getName()).log(Level.SEVERE, null, ex);
                e.printStackTrace();
            }
        }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Invalid User Name and Password !!!");
        }


    }//GEN-LAST:event_lgnBtnActionPerformed

    private void ClsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClsBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ClsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClsBtn;
    private javax.swing.JPasswordField PwdTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton lgnBtn;
    private javax.swing.JTextField userTxt;
    private javax.swing.JLabel usrTxt;
    // End of variables declaration//GEN-END:variables
}
