/*
 * EmployeeRegistration.java
 *
 * Created on July 26, 2016, 1:42 AM
 */

package HRM;

//import ireports.MyiReportViewer;
import ireports.ViewIReport;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author  dell notebook
 */
public class Manager_Reports extends javax.swing.JFrame {
String emp_id;
    /** Creates new form EmployeeRegistration */
    public Manager_Reports() {
        initComponents();
        //txtName.setEnabled(false);
    }
        public Manager_Reports(String p) {
        initComponents();
        emp_id=p;
        //txtName.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnReport_Salary = new javax.swing.JButton();
        btnReport_Employee = new javax.swing.JButton();
        btnReport_Attendance = new javax.swing.JButton();
        btnReport_Loans = new javax.swing.JButton();
        btnReport_Leaves = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("8WARE TOTAL MANAGEMENT SYSTEM");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Reports");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Logged in as Employe Manager");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 153));
        jButton2.setText("Home");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 60, 20));

        jSeparator2.setForeground(new java.awt.Color(51, 153, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 700, 10));

        btnReport_Salary.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReport_Salary.setText("Report Salary");
        btnReport_Salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReport_SalaryActionPerformed(evt);
            }
        });
        getContentPane().add(btnReport_Salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        btnReport_Employee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReport_Employee.setText("Report Employee");
        btnReport_Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReport_EmployeeActionPerformed(evt);
            }
        });
        getContentPane().add(btnReport_Employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        btnReport_Attendance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReport_Attendance.setText("Report Attendance");
        btnReport_Attendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReport_AttendanceActionPerformed(evt);
            }
        });
        getContentPane().add(btnReport_Attendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 150, -1));

        btnReport_Loans.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReport_Loans.setText("Report Loans");
        btnReport_Loans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReport_LoansActionPerformed(evt);
            }
        });
        getContentPane().add(btnReport_Loans, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, -1));

        btnReport_Leaves.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReport_Leaves.setText("Report Leaves");
        btnReport_Leaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReport_LeavesActionPerformed(evt);
            }
        });
        getContentPane().add(btnReport_Leaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 140, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("Logout");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 60, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/rect.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(806, 495));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void btnReport_EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReport_EmployeeActionPerformed
// TODO add your handling code here:
try {
        ViewIReport.allemp();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null,"error in ireport");
    }

}//GEN-LAST:event_btnReport_EmployeeActionPerformed

private void btnReport_SalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReport_SalaryActionPerformed
// TODO add your handling code here:
   try {
        ViewIReport.allsal();
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_btnReport_SalaryActionPerformed

private void btnReport_LoansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReport_LoansActionPerformed
// TODO add your handling code here:
      try {
        ViewIReport.allloans();
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_btnReport_LoansActionPerformed

private void btnReport_AttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReport_AttendanceActionPerformed
// TODO add your handling code here:
              try {
        ViewIReport.allatt();
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_btnReport_AttendanceActionPerformed

private void btnReport_LeavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReport_LeavesActionPerformed
// TODO add your handling code here:
          try {
        ViewIReport.allleaves();
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_btnReport_LeavesActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    new EMPMANAGERHOME().setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    new Login().setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager_Reports().setVisible(true);
            }
        });
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReport_Attendance;
    private javax.swing.JButton btnReport_Employee;
    private javax.swing.JButton btnReport_Leaves;
    private javax.swing.JButton btnReport_Loans;
    private javax.swing.JButton btnReport_Salary;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

}
