/*
 * EmployeeRegistration.java
 *
 * Created on July 26, 2016, 1:42 AM
 */

package HRM;
import java.sql.Connection;
//import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author  dell notebook
 */
public class UpdateEmployee extends javax.swing.JFrame {
    String eid;
    String gender;
    String setString1;
    String setString2;
    /** Creates new form EmployeeRegistration */
    public UpdateEmployee() {
        initComponents();
        //txtName.setEnabled(false);
        
        txtAddress.setText("");
        txtEmail.setText("");
        txtID.setText("");
        txtNIC.setText("");
        txtName.setText("");
        txtPhone.setText("");
        cmbDesignation.setSelectedIndex(0);
        cmbDepartment.setSelectedIndex(0);
        cmbType.setSelectedIndex(0);
        ButtonGroup bg = new ButtonGroup();
        bg.add(chFemale);
        bg.add(chMale);
    }
   


    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblNIC = new javax.swing.JLabel();
        txtNIC = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        chFemale = new javax.swing.JRadioButton();
        chMale = new javax.swing.JRadioButton();
        txtPhone = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        lblDesignation1 = new javax.swing.JLabel();
        lblDepartment1 = new javax.swing.JLabel();
        cmbDesignation = new javax.swing.JComboBox();
        cmbDepartment = new javax.swing.JComboBox();
        btnClear = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("8WARE TOTAL MANAGEMENT SYSTEM");
        setExtendedState(6);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 20, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Update Employee ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Logged in as Employee Manager");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 80, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 153));
        jButton2.setText("Home");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 110, 60, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("Logout");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 110, 60, 20));

        jSeparator2.setForeground(new java.awt.Color(51, 153, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 1280, 10));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblId.setText("Employee ID");
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        txtID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDKeyReleased(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 190, -1));

        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblName.setText("Employee Name");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 190, -1));

        lblAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAddress.setText("Address");
        jPanel1.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 190, -1));

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("Email");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 190, -1));

        lblNIC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNIC.setText("NIC");
        jPanel1.add(lblNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        txtNIC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 190, -1));

        lblGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGender.setText("Gender");
        jPanel1.add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        chFemale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chFemale.setText("Female");
        jPanel1.add(chFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        chMale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chMale.setText("Male");
        jPanel1.add(chMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, -1));

        txtPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 190, -1));

        lblPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPhone.setText("Phone");
        jPanel1.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        lblType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblType.setText("Type");
        jPanel1.add(lblType, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        cmbType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a type", "Training", "Probation", "Temporary", "Permanent" }));
        cmbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeActionPerformed(evt);
            }
        });
        jPanel1.add(cmbType, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 750, 370));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Department Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDesignation1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDesignation1.setText("Designation");
        jPanel2.add(lblDesignation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        lblDepartment1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDepartment1.setText("Department");
        jPanel2.add(lblDepartment1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        cmbDesignation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbDesignation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a designation", "employee", "manager", "technician", "driver" }));
        jPanel2.add(cmbDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 190, -1));

        cmbDepartment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbDepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a department", "HR", "Accounts", "Technical", "Marketing" }));
        jPanel2.add(cmbDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 190, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 160, 440, 370));

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 590, -1, -1));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 590, -1, -1));

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 590, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/rect.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1725, 855));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    new EMPMANAGERHOME().setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

private void txtIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyReleased
// TODO add your handling code here:
        try {

        txtAddress.setText("");
        txtEmail.setText("");
        txtNIC.setText("");
        txtName.setText("");
        txtPhone.setText("");
        cmbDesignation.setSelectedIndex(0);
        cmbDepartment.setSelectedIndex(0);
        cmbType.setSelectedIndex(0);

        setString1 = "like 'txtID.getText()%'";
        setString2 = txtID.getText();
        
        Connection c = DBAccess.getConnection();
        PreparedStatement s;
        s = c.prepareStatement("select * from employee where emp_id='"+txtID.getText()+"'");
        //s.setString(1, "%" + txtID.getText() + "%");
        ResultSet rs = s.executeQuery();


        if (rs.next()) {
            txtID.setText(rs.getString("emp_id"));
            txtID.setEnabled(false);
            txtNIC.setText(rs.getString("nic"));
            txtPhone.setText(rs.getString("phone"));
            txtName.setText(rs.getString("ename"));
            txtAddress.setText(rs.getString("address"));
            txtEmail.setText(rs.getString("email"));
            gender = rs.getString("gender");

            //setting the value to the cmbDesignation
            if (rs.getString("designation").equals("employee")) {
                cmbDesignation.setSelectedIndex(1);
            } else if (rs.getString("designation").equals("manager")) {
                cmbDesignation.setSelectedIndex(2);
            } else if (rs.getString("designation").equals("technician")) {
                cmbDesignation.setSelectedIndex(3);
            } else if (rs.getString("designation").equals("driver")) {
                cmbDesignation.setSelectedIndex(4);
            } else {
                cmbDesignation.setSelectedIndex(0);
            }

            //setting the value to the cmbDepartment
            if (rs.getString("department_name").equals("HR")) {
                cmbDepartment.setSelectedIndex(1);
            } else if (rs.getString("department_name").equals("Accounts")) {
                cmbDepartment.setSelectedIndex(2);
            } else if (rs.getString("department_name").equals("Technical")) {
                cmbDepartment.setSelectedIndex(3);
            } else if (rs.getString("department_name").equals("Marketing")) {
                cmbDepartment.setSelectedIndex(4);
            } else {
                cmbDepartment.setSelectedIndex(0);
            }

            //setting the value to the cmbType
            if (rs.getString("type").equals("Training")) {
                cmbType.setSelectedIndex(1);
            } else if (rs.getString("type").equals("Probation")) {
                cmbType.setSelectedIndex(2);
            } else if (rs.getString("type").equals("Temporary")) {
                cmbType.setSelectedIndex(3);
            } else if (rs.getString("type").equals("Permanent")) {
                cmbType.setSelectedIndex(4);
            } else {
                cmbType.setSelectedIndex(0);
            }



        if(gender.equals("Female"))
        {
       /* chFemale.setEnabled(false); 
        chMale.setEnabled(false); */
        chFemale.setSelected(true); 
        chMale.setSelected(false);  
        }
        else{
        /*chFemale.setEnabled(false); 
        chMale.setEnabled(false); */
        chFemale.setSelected(false); 
        chMale.setSelected(true);  
        }

        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_txtIDKeyReleased

private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtPhoneActionPerformed

private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
// TODO add your handling code here:
        txtAddress.setText("");
        txtEmail.setText("");
        txtID.setText("");
        txtID.setEnabled(true);
        txtNIC.setText("");
        txtName.setText("");
        txtPhone.setText("");
        cmbDesignation.setSelectedIndex(0);
        cmbDepartment.setSelectedIndex(0);
        cmbType.setSelectedIndex(0);
}//GEN-LAST:event_btnClearActionPerformed

private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
// TODO add your handling code here:
    try {
        
        if(chFemale.isSelected())
        {
            gender="Female";
        }
        else
        {
            gender="Male";
        }
        
        Connection c= DBAccess.getConnection();
        Statement s=c.createStatement();
        s.executeUpdate("Update employee set nic='"+txtNIC.getText()+"',phone='"+txtPhone.getText()+"',designation='"+cmbDesignation.getSelectedItem().toString()+"',department_name='"+cmbDepartment.getSelectedItem().toString()+"',type='"+cmbType.getSelectedItem().toString()+"',ename='"+txtName.getText()+"',address='"+txtAddress.getText()+"',email='"+txtEmail.getText()+"',gender='"+gender+"' where emp_id='"+txtID.getText()+"'");
        JOptionPane.showMessageDialog(rootPane, "Updated!!!");
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_btnUpdateActionPerformed

private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
// TODO add your handling code here:
    try {
         Connection c=DBAccess.getConnection();
    Statement s=c.createStatement();
    s.executeUpdate("DELETE FROM employee  where  emp_id='" + txtID.getText() + "' ");
    JOptionPane.showMessageDialog(rootPane, "Deleted !!!");
    
        txtAddress.setText("");
        txtEmail.setText("");
        txtID.setText("");
        txtNIC.setText("");
        txtName.setText("");
        txtPhone.setText("");
        cmbDesignation.setSelectedIndex(0);
        cmbDepartment.setSelectedIndex(0);
        cmbType.setSelectedIndex(0);
        
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_btnDeleteActionPerformed

private void cmbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cmbTypeActionPerformed

private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
// TODO add your handling code here:

}//GEN-LAST:event_txtIDActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    new Login().setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateEmployee().setVisible(true);
            }
        });
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JRadioButton chFemale;
    private javax.swing.JRadioButton chMale;
    private javax.swing.JComboBox cmbDepartment;
    private javax.swing.JComboBox cmbDesignation;
    private javax.swing.JComboBox cmbType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblDepartment1;
    private javax.swing.JLabel lblDesignation1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNIC;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblType;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables

}
