/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accounts;

import HRM.Login;
import java.awt.Color;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Tharushi
 */
public class Add_payments extends javax.swing.JFrame {

    /**
     * Creates new form Transaction_details
     */
    queries qr = new queries();
    validates v = new validates();
    Date d5 = new Date();
    ResultSet rset = null;

    public Add_payments() throws Exception {
        initComponents();
        billId();
        billId1();
        fillEID();
        update_table();
        update_table1();

    }

    void billId() {
        try {
            ResultSet rs = qr.getdata("SELECT MAX(bill_id) FROM petty_cash");
            while (rs.next()) {
                String batch1 = rs.getString("MAX(bill_id)");
                int batch2 = Integer.parseInt(batch1.substring(3));
                int batch3 = (batch2 + 1);
                lblBID2.setText("PID" + batch3);
            }
        } catch (Exception e) {
            lblBID2.setText("PID" + 1001);
        }
    }

    void billId1() {
        try {
            ResultSet rs = qr.getdata("SELECT MAX(billID) FROM payments");
            while (rs.next()) {
                String batch1 = rs.getString("MAX(billID)");
                int batch2 = Integer.parseInt(batch1.substring(3));
                int batch3 = (batch2 + 1);
                lblBID1.setText("BID" + batch3);
            }
        } catch (Exception e) {
            lblBID1.setText("BID" + 1001);
        }
    }

    private void update_table() {

        try {
            rset = qr.fillGridPetty();

            tblPC.setModel(DbUtils.resultSetToTableModel(rset));
        } catch (Exception ex) {
            Logger.getLogger(Add_payments.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void update_table1() {

        try {
            rset = qr.fillGridmonthly();

            tblPC1.setModel(DbUtils.resultSetToTableModel(rset));
        } catch (Exception ex) {
            Logger.getLogger(Add_payments.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    

    public void Clear() {
        lblBID2.setText("");
        txtPrice.setText("");
        Date now = new Date();
        dtpDate.setDate(now);
        txtDiscription.setText("");
        txtEID.setSelectedIndex(0);
        cmbPT.setSelectedIndex(0);

    }

    public void Clear1() {
        lblBID1.setText("");
        txtPrice1.setText("");
        Date now = new Date();
        dtpDate1.setDate(now);
        jComboBox1.setSelectedIndex(0);
        cmbPT1.setSelectedIndex(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblBID2 = new javax.swing.JLabel();
        txtEID = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        cmbPT = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiscription = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnupdare = new javax.swing.JButton();
        dtpDate = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPC = new javax.swing.JTable();
        btnInsert1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnSearch1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnAdd1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtPrice1 = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        btnupdare1 = new javax.swing.JButton();
        dtpDate1 = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPC1 = new javax.swing.JTable();
        lblBID1 = new javax.swing.JLabel();
        cmbPT1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Petty cash and Monthly payments");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setText("Accounts");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/rect.png"))); // NOI18N

        btnLogout.setText("Logout");
        btnLogout.setName("btnLogout"); // NOI18N
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 0));
        jLabel9.setText("Logged in as admin");

        jButton1.setText("Home");

        jSeparator1.setForeground(new java.awt.Color(0, 204, 0));

        jLabel6.setText("Payment Type");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnAdd.setText("Add Payment");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        cmbPT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Cheque" }));
        cmbPT.setName("cmbpaymenttype"); // NOI18N
        cmbPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPTActionPerformed(evt);
            }
        });

        jLabel5.setText("Employee ID");

        jLabel7.setText("Price");

        txtPrice.setName("txtprice"); // NOI18N
        txtPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPriceFocusLost(evt);
            }
        });
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        jLabel2.setText("Bill ID");

        txtDiscription.setColumns(20);
        txtDiscription.setRows(5);
        jScrollPane1.setViewportView(txtDiscription);

        jLabel3.setText("Discription");

        jLabel8.setText("Date");

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnupdare.setText("Update");
        btnupdare.setName("btnUpdate"); // NOI18N
        btnupdare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdareActionPerformed(evt);
            }
        });

        dtpDate.setMaxSelectableDate(d5);

        tblPC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPCMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPC);

        btnInsert1.setText("Insert");
        btnInsert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsert1ActionPerformed(evt);
            }
        });

        jButton2.setText("DEMO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(btnAdd)
                .addGap(28, 28, 28)
                .addComponent(btnInsert1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(199, 199, 199))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addGap(40, 40, 40)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(dtpDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblBID2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel5))
                                    .addGap(40, 40, 40)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmbPT, 0, 199, Short.MAX_VALUE)
                                        .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                        .addComponent(txtEID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(btnupdare)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnSearch)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnDelete)
                            .addGap(228, 228, 228)))
                    .addGap(63, 63, 63)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsert1)
                    .addComponent(btnAdd)
                    .addComponent(jButton2))
                .addContainerGap(278, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(97, 97, 97)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(txtEID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(cmbPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(25, 25, 25)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(lblBID2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(28, 28, 28)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(110, 118, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dtpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGap(17, 17, 17)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSearch)
                        .addComponent(btnupdare)
                        .addComponent(btnDelete))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(41, 41, 41)))
        );

        jTabbedPane1.addTab("Petty Cash", jPanel1);

        jLabel10.setText("Amount");

        jLabel11.setText("Bill ID");

        btnSearch1.setText("Search");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Discription");

        btnAdd1.setText("Add Payment");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electricity Bill", "water Bill", "LandPhone Bill", "Moblie Bill", "Internet Bill", "Monthly Rental", "Tax" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Date");

        txtPrice1.setName("txtprice"); // NOI18N
        txtPrice1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPrice1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrice1FocusLost(evt);
            }
        });
        txtPrice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrice1ActionPerformed(evt);
            }
        });

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnDelete1.setText("Delete");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });

        btnupdare1.setText("Update");
        btnupdare1.setName("btnUpdate"); // NOI18N
        btnupdare1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdare1ActionPerformed(evt);
            }
        });

        dtpDate1.setMaxSelectableDate(d5);

        tblPC1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPC1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblPC1);

        cmbPT1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Cheque" }));
        cmbPT1.setName("cmbpaymenttype"); // NOI18N
        cmbPT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPT1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Payment Type");

        jLabel15.setText("jLabel15");

        jButton3.setText("DEMO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(btnAdd1)
                .addGap(18, 18, 18)
                .addComponent(btnInsert)
                .addGap(18, 18, 18)
                .addComponent(btnupdare1)
                .addGap(18, 18, 18)
                .addComponent(btnSearch1)
                .addGap(18, 18, 18)
                .addComponent(btnDelete1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(34, 34, 34))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(7, 7, 7)
                                    .addComponent(jLabel13)))
                            .addGap(40, 40, 40)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dtpDate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, 0, 169, Short.MAX_VALUE)
                                .addComponent(lblBID1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(52, 52, 52)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmbPT1, 0, 199, Short.MAX_VALUE)
                                        .addComponent(txtPrice1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))))))
                    .addGap(63, 63, 63)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(btnAdd1)
                    .addComponent(btnInsert)
                    .addComponent(btnupdare1)
                    .addComponent(btnSearch1)
                    .addComponent(btnDelete1))
                .addContainerGap(284, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(cmbPT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(25, 25, 25)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(txtPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(lblBID1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(32, 32, 32)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel13))
                        .addComponent(dtpDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(45, 45, 45)))
        );

        jTabbedPane1.addTab("Monthly Payments", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(22, 22, 22))
                                .addComponent(jLabel1)))
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(jButton1))
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillEID() throws Exception {

        ResultSet rset = qr.getEid();
        while (rset.next()) {
            txtEID.addItem(rset.getString(1));
        }
    }
    
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
      new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            ResultSet rs = qr.getDataPetty(lblBID2.getText());

            if (rs.first()) {
                lblBID2.setText(rs.getString("bill_id"));
                txtDiscription.setText(rs.getString("description"));
                txtPrice.setText(rs.getString("price"));

                txtEID.setSelectedItem(rs.getString("emp_id"));
                cmbPT.setSelectedItem(rs.getString("payment_type"));

                String add5 = rs.getString("date");
                SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
                dtpDate.setDate(f.parse(add5));

            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        btnAdd.enable(false);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        DateFormat dyf = new SimpleDateFormat("dd/MM/yyyy");
        String dtstr = dyf.format(dtpDate.getDate()).toString();

        try {

            if (v.isEmpty(txtDiscription.getText()) || v.isEmpty(txtPrice.getText())) {
                JOptionPane.showMessageDialog(null, "Fill all the textboxes");
            } else if (qr.addPaymentPetty(lblBID2.getText(), txtDiscription.getText(), dtstr, cmbPT.getSelectedItem().toString(), Float.parseFloat(txtPrice.getText()), txtEID.getSelectedItem().toString())) {

                JOptionPane.showMessageDialog(null, "Successfully Added");

                Clear();
                billId();
                update_table();
            } else {

                //JOptionPane.showMessageDialog(null,"Error occured during the saving");
            }

        } catch (Exception ex) {
            Logger.getLogger(Add_payments.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void cmbPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPTActionPerformed

    private void txtPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusGained
        txtPrice.setForeground(Color.black);
    }//GEN-LAST:event_txtPriceFocusGained

    private void txtPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusLost

        String sr = txtPrice.getText();

        Pattern p = Pattern.compile("[0-9]+([,.][0-9]{1,2})?");
        Matcher m = p.matcher(sr);
        boolean s = m.matches();
        
        if (m.matches()) {
            System.out.println("accounts.Petty_cash.txtPriceFocusLost()");
        } else {
            txtPrice.setText("");
            txtPrice.setForeground(Color.red);
            txtPrice.setText("Invalid Price");

        }

        
    }//GEN-LAST:event_txtPriceFocusLost

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        int no = JOptionPane.showConfirmDialog(null, "Do you Want to Delete");
        if (no == 0) {
            try {

                if (qr.deletePetty(lblBID2.getText())) {

                    JOptionPane.showMessageDialog(null, "Successfully Deleted");
                    update_table();
                    Clear();

                } else {

                    JOptionPane.showMessageDialog(null, "Error occured during the deleting");
                }

            } catch (Exception ex) {
                Logger.getLogger(Add_payments.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnupdareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdareActionPerformed

        DateFormat dyf = new SimpleDateFormat("dd/MM/yyyy");
        String dtstr = dyf.format(dtpDate.getDate()).toString();

        try {
            if (v.isEmpty(txtDiscription.getText()) || v.isEmpty(txtPrice.getText())) {
                JOptionPane.showMessageDialog(null, "Fill all the textboxes");
            } else if (qr.updatePaymentPetty(lblBID2.getText(), txtDiscription.getText(), dtstr, cmbPT.getSelectedItem().toString(), Float.parseFloat(txtPrice.getText()))) {

                JOptionPane.showMessageDialog(null, "Successfully Updated");
                update_table();
                Clear();

            } else {

                JOptionPane.showMessageDialog(null, "Error occured during the updating");
            }

        } catch (Exception ex) {
            Logger.getLogger(Add_payments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnupdareActionPerformed

    private void tblPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPCMouseClicked
        try {
            txtPrice.setForeground(Color.black);
            int row = tblPC.getSelectedRow();
            String Table_Click = (tblPC.getModel().getValueAt(row, 0).toString());
            ResultSet rs = qr.getDataPetty(Table_Click);

            //JOptionPane.showMessageDialog(null,"Searching done");
            if (rs.next()) {
                //JOptionPane.showMessageDialog(null,"Searching here done");

                String add1 = rs.getString("bill_id");
                lblBID2.setText(add1);
                String add2 = rs.getString("description");
                txtDiscription.setText(add2);
                Float add4 = rs.getFloat("price");
                txtPrice.setText(add4.toString());

                String add5 = rs.getString("date");
                SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
                dtpDate.setDate(f.parse(add5));

                String add6 = rs.getString("payment_type");
                cmbPT.setSelectedItem(add6);

                String add3 = rs.getString("emp_id");
                txtEID.setSelectedItem(add3);

                //JOptionPane.showMessageDialog(null,"Searching here done");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_tblPCMouseClicked

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        try {
            ResultSet rs = qr.getDataMonthly(lblBID1.getText());

            if (rs.first()) {

                lblBID1.setText(rs.getString("billID"));
                jComboBox1.setSelectedItem(rs.getString("description"));
                txtPrice1.setText(rs.getString("price"));
                cmbPT1.setSelectedItem(rs.getString("payment_type"));

                String add5 = rs.getString("date");
                SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
                dtpDate1.setDate(f.parse(add5));

            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //btnAdd1.enable(false);
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed

        DateFormat dyf = new SimpleDateFormat("dd/MM/yyyy");
        //dtpDate.setFormats(dyf);
        String dtstr = dyf.format(dtpDate1.getDate()).toString();

        try {
            if (v.isEmpty(txtPrice1.getText())) {
                JOptionPane.showMessageDialog(null, "Fill all the textboxes");
            } else if (qr.addMontlyPayment(lblBID1.getText(), jComboBox1.getSelectedItem().toString(), dtstr, cmbPT1.getSelectedItem().toString(), Float.parseFloat(txtPrice1.getText()))) {

                JOptionPane.showMessageDialog(null, "Successfully Added");

                Clear1();
                billId1();
                update_table1();
                billId1();
            } else {

                JOptionPane.showMessageDialog(null, "Error occured during the saving");
            }

        } catch (Exception ex) {
            Logger.getLogger(Add_payments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtPrice1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrice1FocusGained
        txtPrice1.setForeground(Color.black);
    }//GEN-LAST:event_txtPrice1FocusGained

    private void txtPrice1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrice1FocusLost

        String sr = txtPrice1.getText();

        Pattern p = Pattern.compile("[0-9]+([,.][0-9]{1,2})?");
        Matcher m = p.matcher(sr);
        //boolean s = m.matches();
        //System.out.println(s);
        if (m.matches()) {
            System.out.println("accounts.Monthly_payments.txtPriceFocusLost()");
        } else {
            txtPrice1.setText("");
            txtPrice1.setForeground(Color.red);
            txtPrice1.setText("Invalid Price");

        }

        /*String[] arr= txtPrice.getText().split(".");
        System.out.println(arr[0]);
        if(arr.length==2){
            if(arr[1].length()==2 || arr[0].matches("[0-9]+")||arr[1].matches("[0-9]+"))
            {

            }
            else{
                txtPrice.setText("");
                txtPrice.setForeground(Color.red);
                txtPrice.setText("Invalid Price");
            }
        }
        else{
            txtPrice.setText("");
            txtPrice.setForeground(Color.red);
            txtPrice.setText("Add price in rupees.cents format");
        }*/
    }//GEN-LAST:event_txtPrice1FocusLost

    private void txtPrice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrice1ActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        Clear1();
        billId1();
        update_table1();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed

        int no = JOptionPane.showConfirmDialog(null, "Do you Want to Delete");
        if (no == 0) {
            try {

                if (qr.deletemonthly(lblBID1.getText())) {

                    JOptionPane.showMessageDialog(null, "Successfully Deleted");
                    update_table1();
                    Clear1();

                } else {

                    JOptionPane.showMessageDialog(null, "Error occured during the deleting");
                }

            } catch (Exception ex) {
                Logger.getLogger(Add_payments.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnupdare1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdare1ActionPerformed

        DateFormat dyf = new SimpleDateFormat("dd/MM/yyyy");
        //dtpDate.setFormats(dyf);
        String dtstr = dyf.format(dtpDate1.getDate()).toString();

        try {
            if (v.isEmpty(txtPrice1.getText())) {
                JOptionPane.showMessageDialog(null, "Fill all the textboxes");
            } else if (qr.updateMonthlyPayment(lblBID1.getText(), jComboBox1.getSelectedItem().toString(), dtstr, cmbPT1.getSelectedItem().toString(), Float.parseFloat(txtPrice1.getText()))) {

                JOptionPane.showMessageDialog(null, "Successfully Updated");
                update_table1();
                Clear1();

            } else {

                JOptionPane.showMessageDialog(null, "Error occured during the updating");
            }

        } catch (Exception ex) {
            Logger.getLogger(Add_payments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnupdare1ActionPerformed

    private void tblPC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPC1MouseClicked
        try {
            txtPrice1.setForeground(Color.black);
            int row = tblPC1.getSelectedRow();
            String Table_Click = (tblPC1.getModel().getValueAt(row, 0).toString());
            ResultSet rs = qr.getDataMonthly(Table_Click);

            //JOptionPane.showMessageDialog(null,"Searching done");
            if (rs.next()) {
                //JOptionPane.showMessageDialog(null,"Searching here done");

                String add1 = rs.getString("billID");
                lblBID1.setText(add1);
                String add2 = rs.getString("description");
                jComboBox1.setSelectedItem(add2);
                Float add4 = rs.getFloat("price");
                txtPrice1.setText(add4.toString());

                String add5 = rs.getString("date");
                SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
                dtpDate1.setDate(f.parse(add5));

                String add6 = rs.getString("payment_type");
                cmbPT1.setSelectedItem(add6);

                //JOptionPane.showMessageDialog(null,"Searching here done");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_tblPC1MouseClicked

    private void cmbPT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPT1ActionPerformed

    private void btnInsert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsert1ActionPerformed
        Clear();
        billId();
        update_table();
    }//GEN-LAST:event_btnInsert1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtDiscription.setText("Fuel");
        txtPrice.setText("2500.00");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        txtPrice1.setText("2330.25");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Add_payments().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Add_payments.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnInsert1;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnupdare;
    private javax.swing.JButton btnupdare1;
    private javax.swing.JComboBox<String> cmbPT;
    private javax.swing.JComboBox<String> cmbPT1;
    private com.toedter.calendar.JDateChooser dtpDate;
    private com.toedter.calendar.JDateChooser dtpDate1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBID1;
    private javax.swing.JLabel lblBID2;
    private javax.swing.JTable tblPC;
    private javax.swing.JTable tblPC1;
    private javax.swing.JTextArea txtDiscription;
    private javax.swing.JComboBox<String> txtEID;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtPrice1;
    // End of variables declaration//GEN-END:variables
}
